beholdr/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from search import views as search_views
from podcast import views as podcast_views
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls



urlpatterns = [
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^vhs/',  podcast_views.vhs, name='vhs'),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^tools/simplecast/', include('simple_cast.urls',\
                                       namespace="simple_cast")),
    url(r'^tools/iTunesReviews/', include('iTunesReviews.urls', \
                                    namespace ="iTunesReviews")),
    
    url(r'', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iTunesReviews/urls.py
from django.conf.urls import url

from iTunesReviews.views import main, runReport, search, progressPage

urlpatterns = [
    url(r'^$', main, name='main'),
    url(r'^report$', progressPage, name='progressPage'),
    url(r'^searchid$', search, name = 'search'),
]

iTunesReviews/models.py
from django.db import models

class ReviewReport(models.Model):
    name = models.TextField()
    book = models.FilePathField(path="tempXls")
    counter = models.IntegerField(default=0)

class Report(models.Model):
    book = models.TextField()

# Create your models here.

iTunesReviews/views.py
import sys
from .models import ReviewReport
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader, RequestContext
from django import forms
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from os import path, chdir, remove
import itunesreviewreport
import io, random
from collections import OrderedDict
from openpyxl import Workbook
from openpyxl import load_workbook
from openpyxl.writer.excel import save_virtual_workbook

from django.views.generic import TemplateView

def main(request,ID = ""):

    try:
        ID = request.POST['ID']
    except:
        ID = ""

    countryfile=0;

    #get the country list
    #run through the country list file and generate country objects with the country codes and names
    try:
        newPath = path.abspath(path.dirname(__file__))
        chdir(newPath)
        
    except Exception, e:
        return HttpResponse("INTERNAL ERROR: countryList not opened, file missing from app folder")

    try:
        countryfile = open("countrylist.csv").readlines()
        #parse countryfile into dictionary {Region:[country1,country2...],...}
        countryDict = {}
        for c in countryfile:
            sp = c.split(',')
            try:
                countryDict[sp[2]].append(sp[0]+","+sp[1])
            except:
                countryDict[sp[2]] = [sp[0]+","+sp[1]]

        #return HttpResponse(sorted(countryDict.items()))

        sortedCountryDict = OrderedDict(sorted(countryDict.items()))

    except:
        return HttpResponse("can't open countryList, file missing from app folder")
    
    template = loader.get_template('itunesreviews/main.html')
    context = RequestContext(request, {'country_list' : sortedCountryDict, 'Ident':ID,})
    return HttpResponse(template.render(context))


def progressPage(request):
    try:
        idnumber = request.POST['id']
        countryList = request.POST.getlist('countryList[]')
    except:
        return redirect("../iTunesReviews")
    try:
        seshId = (request.POST['seshId'])
    #Generate session id
    except:
        random.seed()
        seshId = str(random.randrange(10001, 20000, 1))
        #print >>sys.stderr, seshId
    try:
        if(len(countryList) >0):
            if(int(idnumber) < 10000000000 and int(idnumber) >= 100000000):        
                #get the next 4 countries
                workingCountryList=[]
                for x in range(0, 1):
                    try:
                        workingCountryList.append(countryList[0])
                        countryList.pop(0)
                    except:
                        break

                runReport(idnumber, workingCountryList, seshId)
                        
                template = loader.get_template('itunesreviews/progress.html')
                context = RequestContext(request, {'country_list':countryList, 'Ident':idnumber,
                                                           'seshId':seshId,})
                return HttpResponse(template.render(context))
                        
        else:
            #now we're going to returnt he actual report and delete the internal records
            rep= ReviewReport.objects.get(name=seshId)
            
            newPath = path.abspath(path.dirname(__file__))
            chdir(newPath)
            
            returnBook = load_workbook(rep.book)
            returnBook = save_virtual_workbook(returnBook)
            
            #delete the actual file
            newPath = path.abspath(path.dirname(__file__))
            chdir(newPath)
            remove(rep.book)
            
            #delete database entry
            rep.delete()
            
            #return as attachment
            response = HttpResponse(returnBook ,content_type='application/vnd.ms-excel')
            response['Content-Disposition'] = 'attachment; filename="iTunesReviews.xls"'
            return response
    except:
        return redirect("../iTunesReviews")

def runReport(idnumber, countryList, sessionId):
        
    if(int(idnumber) < 10000000000 and int(idnumber) >= 100000000):
        
        try:
            newPath = path.abspath(path.dirname(__file__))
            chdir(newPath)
            
        except Exception, e:
            return HttpResponse("INTERNAL ERROR: file locations missing")             
            
        try:
            rep = ReviewReport.objects.get(name=sessionId)
            bookAddress = rep.book
            try:
                book = load_workbook(bookAddress)
                summarySheet = book.get_sheet_by_name("Summary")
                #print >>sys.stderr, countryList

                book = itunesreviewreport.report(idnumber,countryList,
                                                 book,summarySheet, rep.counter)
                rep.counter += len(countryList)
                rep.save()
                    
                book.save(rep.book)

                #print >>sys.stderr, rep.counter 

                return(book)
            except Exception, e:
                #print >>sys.stderr, e    
                rep.delete()
                return runReport(idnumber, countryList, sessionId);
        
        
        except ObjectDoesNotExist:
            #print >>sys.stderr, "no exist"

            #create book path database entry. 
            #Counter set to 2 as the first writeable row on the summary page
            rep = ReviewReport(name=sessionId, book = '', counter=2) 
            #create the workbook
            book = Workbook()
            #create the summary page
            summarySheet = book.create_sheet()
            summarySheet.title = "Summary"    
            summarySheet.cell(row=1,column=1).value = "Country"
            summarySheet.cell(row=1,column=2).value = "Reviews"
            #remove the default sheet
            book.remove_sheet(book.get_sheet_by_name("Sheet"))

            #save the book and the db entry
            book.save("tempXls/"+sessionId+".xlsx") 
            rep.book= "tempXls/"+sessionId+".xlsx"
            rep.save()
            return runReport(idnumber, countryList, sessionId)
            
        except MultipleObjectsReturned:
            rep = ReviewReport.objects.filter(name=sessionId)
            rep.delete()
            return runReport(idnumber, countryList, sessionId+'2')
            
    else:
        #pass a list with the next country to do
        return HttpResponse("itunes id error, " +  idnumber +  " not in range")
            
def search(request):
    try:
        name = request.POST['name']
    except:
        name = ""

    template = loader.get_template('itunesreviews/search.html')

    #if there is a search term do the search, otherwise render the empty results page
    if(name != None and name != ""):
        context = RequestContext(request, {'results' : itunesreviewreport.idLookup(name), 'SearchTerm':name,})
        return HttpResponse(template.render(context))
    else:
        context = RequestContext(request, {'SearchTerm':name,})
        return HttpResponse(template.render(context))

#itunesreviewreport.report(903688996)

search/views.py
from __future__ import absolute_import, unicode_literals

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render

from wagtail.wagtailcore.models import Page
from wagtail.wagtailsearch.models import Query


def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return render(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

iTunesReviews/templates/itunesreviews/main.html
{% extends "base.html"%}

{% load staticfiles %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
{% load bootstrap3 %}
{% bootstrap_css %}
<link rel="stylesheet" type="text/css" href="{% static 'iTunesReviews/style.css' %}">
{% bootstrap_javascript %}

{% block extra_js %}

<script language = "JavaScript">
  window.onload = function v(){
    document.getElementById("reviews").className = "active";
  }


 function checkAll(ele) {
     var checkboxes = document.getElementsByTagName('input');
     var others = document.getElementsByName('checkAllRegion')
     if (ele.value=="Check All") {
         for (var i = 0; i < checkboxes.length; i++) {
             if (checkboxes[i].type == 'checkbox') {
                 checkboxes[i].checked = true;
             }
         }
     for(var p = 0; p< others.length; p++){
       others[p].value = "Uncheck All";
       others[p].style.backgroundColor="99CCCC";
     }
     ele.value = "Uncheck All";
     ele.style.backgroundColor="99CCCC";
     } else {
         for (var i = 0; i < checkboxes.length; i++) {
             if (checkboxes[i].type == 'checkbox') {
                 checkboxes[i].checked = false;
             }
         }
     checkboxes[3].value = "Check All";
     ele.style.backgroundColor="white";
     for(var p = 0; p< others.length; p++){
       others[p].value = "Check All";
       others[p].style.backgroundColor="white";
     }
     }
   }

   function checkBlock(ele) {
     var name = ele.name;
     var div = document.getElementById(ele.id);
     var checkboxes = div.getElementsByTagName('input')
     if (ele.value=="Check All") {
       for (var i = 0; i < checkboxes.length; i++) {
         if (checkboxes[i].type == 'checkbox') {
           checkboxes[i].checked = true;
         }
       }
       ele.value = "Uncheck All";
       ele.style.backgroundColor="99CCCC";
       }
       else {
         for (var i = 0; i < checkboxes.length; i++) {
             if (checkboxes[i].type == 'checkbox') {
                 checkboxes[i].checked = false;
             }
         }

       ele.value = "Check All";
       ele.style.backgroundColor = "white";
       }
     }

 function validateForm() {
   var x = document.forms["idForm"]["id"].value;
   var y = document.forms["idForm"]["countryList[]"];
   console.log(y[0].checked);
   if(x == null || x == ""){
     document.getElementById("errors").innerHTML = '<div style="color:red; font-size:70%;">Missing iTunes ID</div>'
     return false;
   }
   if(x<100000000 || x > 9999999999 ||isNaN(x)){
     document.getElementById("errors").innerHTML = '<div style="color:red; font-size:70%;">iTunes ID out of range - 9 or 10 digit number </div>'
     return false;
   }
   var countryFound = false;
   for(var k = 0; k < y.length; k++){
      if(y[k].checked == true){
        countryFound = true;
        break;
      }
   }
   if(countryFound == false){
     document.getElementById("errors").innerHTML = '<div style="color:red; font-size:70%;">No Countries Selected</div>'
     return false;
   }
   document.getElementById("errors").innerHTML = ''
 }

</script>
{% endblock %}

<body>

{%block content%}
  <div class="container">
    <form class="form-inline" name = "idForm" action="{% url 'iTunesReviews:progressPage' %}" onsubmit="return validateForm()" method="post">
      {% csrf_token %}
      <div class="form-group" id="search">
        <label for="your_name">Enter iTunes ID </label>
        <input id="searchBox" class="form-control" min="100000000" max="9999999999" name="id" value="{{Ident}}">
        <input id="searchButton" class="btn btn-default" type="submit" value="Collect Reviews and Download">
        <p id="errors"></p>
      </div>

      {% if country_list %}
      <p><input class="btn btn-default" type="button" onclick= "checkAll(this)" name = "checkUncheck" value = "Check All"> </p>
        <div class="panel-group" id="accordion">
        {% for key, values in country_list.items %}
          <div class ="row">
            <div class="col-md-8">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{forloop.counter}}">
                    <h4 class="panel-title", style="color:black;">
                      {{key}}
                    </h4>
                  </a>
                </div>
                <div id="collapse{{forloop.counter}}" class="panel-collapse collapse">
                  <div class="panel-body" id="{{key}}">
                    {% for con in values %}
                      <label >
                        <input class="hiddenCheckBox" id="{{con}}" type = "checkbox" name= "countryList[]" value="{{con}}" >
                        <span  class="btn btn-default ">{{con|slice:"3:"}}</span>
                      </label>
                      <br>
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <p><input class="btn btn-default" id="{{key}}" name="checkAllRegion" type="button" onclick= "checkBlock(this)" value = "Check All"> </p>
            </div>
            </div>

          {% endfor %}
        </div>
      {% else %}
        <p>country list missing!</p>
      {% endif %}

    </form>
  </div>
  {% endblock %}

</body>

iTunesReviews/templates/itunesreviews/progress.html
{% extends "base.html"%}

{% load staticfiles %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

{% load bootstrap3 %}
{% bootstrap_css %}

<link rel="stylesheet" type="text/css" href="{% static 'iTunesReviews/style.css' %}">
{% bootstrap_javascript %}

{% block extra_js %}
<script language = "JavaScript">

  window.onload = function (){
    document.getElementById("reviews").className = "active";
    document.forms["idForm"].submit();
  }


</script>
{% endblock %}

<body>

{%block content%}

  <div class="container">

    <form class="form-inline" name = "idForm"  action="" method="POST">
      {% csrf_token %}
      <div class="well"> <h2> <strong> {{Ident}} </strong> </h2>
      <input id="searchBox" hidden="true" class="" min="100000000" max="9999999999" name="id" value="{{Ident}}">
      <input hidden="true" name="seshId" value="{{seshId}}">
      </div>
      <p></p>
      {% if country_list %}
        {%for c in country_list%}
          {%if forloop.counter == 1 %}
            <div class="well" style="background-color:99CCCC;"><p>
              <input id="{{c}}" type = "checkbox" hidden="true" checked="true" name= "countryList[]" value="{{c}}">
            {{c|slice:"3:"}}</p></div>
          {% else %}
            <div class="well"><p>
              <input id="{{c}}" type = "checkbox" hidden="true" checked="true" name= "countryList[]" value="{{c}}">
              {{c|slice:"3:"}}</p></div>
          {%endif%}
        {%endfor%}
      {%else%}
        <div class="well" style="background-color:99CCCC;">Collection complete, your file should now download</div>
      {%endif%}
    </form>
  </div>

  {% endblock %}


</body>

iTunesReviews/templates/itunesreviews/search.html
{% extends "base.html"%}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
{% load bootstrap3 %}
{% bootstrap_css %}
{% load staticfiles %}
{% bootstrap_javascript %}
<link rel="stylesheet" type="text/css" href="{% static 'iTunesReviews/style.css' %}" />

{%block scripts%}
<script language = "JavaScript">
  window.onload = function(){
    var x = document.getElementById("idfinder");
    x.className = "active";
  }
</script>
{%endblock%}

<body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="../home" style="color:black;"><b>Beholdr</b></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="./">iTunes Reviews</a></li>
          <li class="active"><a href="#">iTunes Id Search</a></li>
        </ul>

      </div><!--/.nav-collapse -->
    </div>
  </nav>

{% block content %}

  <div class="container">
    <div>
      <form class="form-inline" name = "search" action="{% url 'iTunesReviews:search' %}" method="post">
        {% csrf_token %}
        <div class ="row" id="search">
          <div class="col-md-2"><label for="your_name">Search by name for iTunes id </label></div>
          <div class="col-md-2"><input id="searchBox" class="form-control" type="text" name="name" value="{{SearchTerm}}"></div>
          <div class="col-md-2"><input id="searchButton" class="btn btn-default" type="submit" value="Go"></div>
        </div>
      </form>
    </div>
    <div>
      {% if results %}
          <table class = "table table-hover">
            <tr>
              <td>iTunes id</td>
              <td>Type</td>
              <td>Artist</td>
              <td>Track Name</td>
            {% for r in results %}
              <form name = "results" action="{% url 'iTunesReviews:main' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="ID" value= {{r.0}}>
                  <tr>
                    {% for k in r %}
                      <td>
                        {%if forloop.counter == 5%}
                          <img src="{{k}}" onError="this.onerror=null;this.src='';" />
                        {% elif forloop.counter == 1 %}
                          <button class = "btn btn-default" style="font-size:100%;">
                            {{k}}
                          </button>
                        {% else %}
                          {{k|truncatechars:30}}

                        {% endif %}
                      </td>
                    {% endfor %}
                  </tr>
              </form>
            {% endfor %}
          </table>
      {% endif %}
    </div>
  </div>
{%endblock%}
</body>